# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=256, verbose_name='Room name')),
                ('count', models.CharField(max_length=256, verbose_name='Count of places')),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Room',
            },
        ),
    ]
