# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='emp_number',
            field=models.CharField(max_length=256, verbose_name='Count of places'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='map.Room'),
            preserve_default=False,
        ),
    ]
